pathTables    = 'app/test/data/tablas/tabla'
pathTexts     = 'app/test/data/textos/carta'
pathWeb       = 'app/test/data/web/web'
pathTimes     = 'app/test/data/times/spanishText_10000_15000'
pathDocuments = 'app/test/data/testHandler' 
nameDocuments = 'document_test'