ERROR_RANGE_PERCENTAGE_DB: float             = 0.25
MEASURE_FOR_TEXTS_WITHOUT_CONTEXTS: float    = 0.75
MEASURE_TO_COLUMN_KEY_REFERS_TO_NAMES: float = 0.75
MINIMAL_WHITE_SPACE_DENSITY: float           = 0.1
MAXIMUM_NUMBER_OF_ELEMENTS_IN_A_REGEX: int   = 4000
