ERROR_RANGE_PERCENTAGE_DB: float             = 0.5
MEASURE_FOR_TEXTS_WITHOUT_CONTEXTS: float    = 0.8
MEASURE_TO_COLUMN_KEY_REFERS_TO_NAMES: float = 0.75
MINIMAL_UPPER_CHAR_DENSITY: float            = 0.8
MAXIMUM_NUMBER_OF_ELEMENTS_IN_A_REGEX: int   = 4000

SAMPLE_DATA_TO_CHOOSE_NAMES:float            = 0.25
MAXIMUM_NUMBER_OF_POSSIBLE_NAMES_FOR_A_QUERY: float = 100