"""initial database migration

Revision ID: 53262b02ce6f
Revises: 
Create Date: 2019-12-21 09:24:14.173520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53262b02ce6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fileLog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('folder', sa.String(length=255), nullable=False),
    sa.Column('isDelete', sa.Boolean(), nullable=False),
    sa.Column('filetype', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fileLog')
    # ### end Alembic commands ###
